name: auth_repository
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  inmemory_cache:
    path: ../inmemory_cache

  uuid_extensions:
    path: ../uuid_extensions

  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
