name: mahjong_ranking_app
description: Mahjong Ranking Mobile App

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  flutter_bloc: ^8.0.0
  dio: ^4.0.6
  sqflite: ^2.0.2
  bottom_navy_bar: ^6.0.0
  json_annotation: ^4.4.0
  wakelock: ^0.6.1
  flutter_form_builder: ^7.1.1
  flutter_local_notifications: ^9.4.0
  permission_handler: ^9.2.0
  equatable: ^2.0.3
  connectivity_plus: ^2.2.1
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  google_sign_in: ^5.3.0
  auth_buttons: ^2.0.4
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  flow_builder: ^0.0.6
  uuid: ^3.0.4
  url_launcher: ^6.1.0
  flutterfire_ui: ^0.4.0+4
  package_info_plus: ^1.4.2

  games_connector:
    path: packages/games_connector

  games_repository:
    path: packages/games_repository

  offline_games_connector:
    path: packages/offline_games_connector

  seed_games_connector:
    path: packages/seed_games_connector

  auth_repository:
    path: packages/auth_repository

  uuid_extensions:
    path: packages/uuid_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  dart_style: ^2.2.3

flutter:

  uses-material-design: true
