name: games_connector
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0
  uuid: ^3.0.4
  uuid_json:
    path: ../uuid_json

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.17.0